language: python

services: docker

before_script:
  - cd provision/files/master/src/scorify
  - make pull

script:
  - ls -al
  - make build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PWD ;
      make push ;
    fi
-
