---
- hosts: docker
  tasks:
    - name: Turn off swap
      shell: swapoff -a
    - name: Install Docker-CE
      import_role:
        name: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_users:
          - vagrant
