# FROM python:3.6-slim

# RUN pip install pipenv
# RUN mkdir -p /usr/src/scorify/worker-peak  /usr/src/scorify/utils

# COPY worker-peak/Pipfile* /usr/src/scorify/worker-peak/

# WORKDIR /usr/src/scorify/worker-peak
# ENV PIP_NO_CACHE_DIR=false
# RUN pipenv install

# COPY ./*.py /usr/src/scorify/
# COPY ./worker-peak /usr/src/scorify/worker-peak/
# COPY ./utils /usr/src/scorify/utils/

# WORKDIR /usr/src/scorify/worker-peak
# CMD ["pipenv", "run", "python", "main.py"]

FROM python:3.6-slim

RUN mkdir -p /usr/src/scorify/worker-peak  /usr/src/scorify/utils
WORKDIR /usr/src/scorify/worker-peak

COPY worker-peak/Pipfile* ./

RUN pip install pipenv && \
  apt-get update && \
  apt-get install -y --no-install-recommends gcc python3-dev libssl-dev && \
  pipenv install --skip-lock && \
  apt-get remove -y gcc python3-dev libssl-dev && \
  apt-get autoremove -y && \
  pip uninstall pipenv -y

COPY ./*.py ../
COPY ./worker-peak ./
COPY ./utils ../utils/
