FROM python:3.6-slim

RUN pip install pipenv
RUN mkdir -p /usr/src/scorify/worker-split  /usr/src/scorify/utils

WORKDIR /usr/src/scorify/worker-split

COPY worker-split/Pipfile* ./

RUN pip install pipenv && \
  apt-get update && \
  apt-get install -y --no-install-recommends gcc python3-dev libssl-dev && \
  pipenv install --deploy --system && \
  apt-get remove -y gcc python3-dev libssl-dev && \
  apt-get autoremove -y && \
  pip uninstall pipenv -y

COPY ./*.py ../
COPY ./worker-split ./
COPY ./utils ../utils/

ENV PYTHONPATH /usr/src/scorify
ENV REDIS_HOST redis
ENV REDIS_PORT 6379

CMD ["python", "main.py"]
