FROM python:3.7-slim

RUN pip install pipenv
RUN mkdir -p /usr/src/scorify/worker-peak  /usr/src/scorify/utils

COPY worker-peak/Pipfile* /usr/src/scorify/worker-peak/

WORKDIR /usr/src/scorify/worker-peak
RUN pipenv install

COPY ./*.py /usr/src/scorify/
COPY ./worker-peak /usr/src/scorify/worker-peak/
COPY ./utils /usr/src/scorify/utils/

WORKDIR /usr/src/scorify/worker-peak
CMD ["pipenv", "run", "python", "main.py"]
