FROM python:3.7-slim

RUN pip install pipenv
RUN mkdir -p /usr/src/scorify/web  /usr/src/scorify/utils

COPY web/Pipfile* /usr/src/scorify/web/

WORKDIR /usr/src/scorify/web
RUN pipenv install

COPY ./*.py /usr/src/scorify
COPY ./web /usr/src/scorify/web/
COPY ./utils /usr/src/scorify/utils/

WORKDIR /usr/src/scorify/web
CMD ["pipenv", "run", "python", "main.py"]
